import breadcrumbInstaller from './components/breadcrumb';
import buttonInstaller from './components/button';
import calloutInstaller from './components/callout';
import checkboxInstaller from './components/checkbox';
import choiceFieldGroupInstaller from './components/choice_field_group';
import contextualMenuInstaller from './components/contextual_menu';
import datePickerInstaller from './components/date_picker';
import dialogInstaller from './components/dialog';
import dropdownInstaller from './components/dropdown';
import labelInstaller from './components/label';
import linkInstaller from './components/link';
import messageBarInstaller from './components/message_bar';
import overlayInstaller from './components/overlay';
import panelInstaller from './components/panel';
import progressIndicatorInstaller from './components/progress_indicator';
import spinnerInstaller from './components/spinner';
import tableInstaller from './components/table';
import textFieldInstaller from './components/text_field';
import toggleInstaller from './components/toggle';

export default function (Vue) {
  breadcrumbInstaller(Vue);
  buttonInstaller(Vue);
  calloutInstaller(Vue);
  checkboxInstaller(Vue);
  choiceFieldGroupInstaller(Vue);
  contextualMenuInstaller(Vue);
  datePickerInstaller(Vue);
  dialogInstaller(Vue);
  dropdownInstaller(Vue);
  labelInstaller(Vue);
  linkInstaller(Vue);
  messageBarInstaller(Vue);
  overlayInstaller(Vue);
  panelInstaller(Vue);
  progressIndicatorInstaller(Vue);
  spinnerInstaller(Vue);
  tableInstaller(Vue);
  textFieldInstaller(Vue);
  toggleInstaller(Vue);
}
